IDIR = /Users/baorenyi/test_workspaces/leveldb/include/
CC = g++
CFLAGS = -I$(IDIR)
 
LDIR = /Users/baorenyi/test_workspaces/leveldb/out-static/libleveldb.a
 
LIBS = -lpthread

all: 
	g++ -o main main.cpp $(LDIR) $(CFLAGS) $(LIBS)
 
